runtime: nodejs
env: flex

env_variables:
  APP_URL: 'https://vaga-prod-lcwaejejlq-ew.a.run.app'
  NEXTAUTH_SECRET: 'NArBDTMHof0EGTx66MFpwk3KRHMNTeUfxvLhbYv14eY=KSZuoIlwu6EDObzRWCVunSUmzjSCIajveR1qZCZIpNk'
  DATABASE_URL: 'mongodb+srv://vaga:CTl9zvmCEsmxonmE@vagabond.wmjbsmj.mongodb.net/test'
  SHADOW_DATABASE_URL: 'mongodb+srv://vaga:CTl9zvmCEsmxonmE@vagabond.wmjbsmj.mongodb.net/test'
  EMAIL_FROM: 'vagabond@vaga.network'
  EMAIL_SERVER_USER: 'apikey'
  EMAIL_SERVER_PASSWORD: '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'
  EMAIL_SERVICE: 'SendGrid'
  EMAIL_SERVER_HOST: 'smtp.sendgrid.net'
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: '308214997'
  LOGSNAG_API_URL: 'https://api.logsnag.com/v1/log'
  LOGSNAG_API_TOKEN: '221f5367efbb957517dd050f0208e74f'
  NEXT_PUBLIC_PUBLISHABLE_KEY: 'pk_test_51JG6mgF8IiCGwPHuN3xk8RpP0v9zAGkzpRG8rE6VceM2gIcPe7OmrW2XVgUKqyKg1AUC3pcx3Jxl6srxqeATJNa600RZDWTz5p'
  PAYMENTS_SECRET_KEY: 'sk_test_51JG6mgF8IiCGwPHuRd8oOqX6nmjgV4G8BQJ1Yk5EXK0jvLQMBpImXe1bwhnxMZe4NjM1HXjNX8rczD0944eFTTuV00T4sofyGs'
  PAYMENTS_SIGNING_SECRET: 'whsec_9zKDJCbkcv8FLMS8aMlanMlQkBDTMFmP'
  APIKEY: 'AIzaSyDVIG2SzKEwiisQU1g3CCS1P-CDCHQ0yY0'
  AUTH_DOMAIN: 'vagabondproduction.firebaseapp.com'
  PROJECT_ID: 'vagabondproduction'
  STORAGE_BUCKET: 'vagabondproduction.appspot.com'
  MESSAGING_SENDER_ID: '134574503875'
  APPID:1:134574503875: 'web:2f05b6c1bab4176582af76'
  MEASSUREMENTID: 'G-GCK5YDDJNE'
  GOOGLE_ID: '74620928473-jgf126pha5jqrrom50nqosk9jo4va7it.apps.googleusercontent.com'
  GOOGLE_SECRET: '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'
  GOOGLE_MAPS_API: 'AIzaSyDpKjLFC4w__kdTMWGfThvN1V7Lmnp3z7w'
  OPENAI_API_KEY: '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'
  AI_PROMPT: 'undefined'
  AI_TEMP: '0'
  AI_MAX_TOKENS: '2048'
  OPENAI_API_ORG: 'org-26DG80KvB7Va2CgmbObdiOWR'
  NEXT_PUBLIC_GOOGLE_MAPS_API: 'AIzaSyDpKjLFC4w__kdTMWGfThvN1V7Lmnp3z7w'
  NEXT_PUBLIC_DHLAPI: 'V9BNtGAjMC0Ar8PIVBhwFCKBK8O6Dd0f'
  NEXT_PUBLIC_DHLSECRET: 'OyjkAGI4NewGbqfd'
  NEXT_PUBLIC_DOCUSIGN_SECRETE: 'a21f6da4-d335-4178-9433-d9c5df6c319c'
  NEXT_PUBLIC_DOCUSIGN_INTEGRATION: '8e0b675d-62c4-4e25-b70d-7dde8270da43'
  UNLOCK_KEY: 'pMpPm%Wc@_gDwHB%bUd9vJQe=L5WwMJKzCvn_MCdwHEb-'

automatic_scaling:
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20
readiness_check:
  path: '/api/ping'
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
handlers:
  - url: /.*
    secure: always
    script: auto
