runtime: nodejs
env: flex

automatic_scaling:
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20
readiness_check:
  path: '/api/ping'
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
handlers:
  - url: /.*
    secure: always
    script: auto
